# End of File
# #####################################################################
# Automatically generated by qmake (2.01a) Mi Jun 10 17:46:48 2009
# #####################################################################
# Input
HEADERS += ./stubs/TelepathyQt4/pending-operation.h
HEADERS += ./stubs/TelepathyQt4/account-manager.h
HEADERS += ./stubs/TelepathyQt4/account.h
HEADERS += ./stubs/TelepathyQt4/types.h
HEADERS += ./stubs/TelepathyQt4/pending-ready.h

SOURCES += ./stubs/TelepathyQt4/pending-operation.cpp
SOURCES += ./stubs/TelepathyQt4/pending-ready.cpp
SOURCES += ./stubs/TelepathyQt4/account-manager.cpp
SOURCES += ./stubs/TelepathyQt4/account.cpp
SOURCES += ./stubs/TelepathyQt4/types.cpp
