# End of File
# #####################################################################
# Automatically generated by qmake (2.01a) Mi Jun 10 17:46:48 2009
# #####################################################################
# Input
HEADERS += ./stubs/TelepathyQt4/pending-operation.h
HEADERS += ./stubs/TelepathyQt4/ready-object.h
HEADERS += ./stubs/TelepathyQt4/account-manager.h
HEADERS += ./stubs/TelepathyQt4/account.h
HEADERS += ./stubs/TelepathyQt4/types.h
HEADERS += ./stubs/TelepathyQt4/pending-ready.h
HEADERS += ./stubs/TelepathyQt4/abstract-interface.h
HEADERS += ./stubs/TelepathyQt4/constants.h
HEADERS += ./stubs/TelepathyQt4/channel.h
HEADERS += ./stubs/TelepathyQt4/connection.h
HEADERS += ./stubs/TelepathyQt4/contact.h
HEADERS += ./stubs/TelepathyQt4/dbus-proxy.h
HEADERS += ./stubs/TelepathyQt4/message.h
HEADERS += ./stubs/TelepathyQt4/presence.h
HEADERS += ./stubs/TelepathyQt4/referenced-handles.h
HEADERS += ./stubs/TelepathyQt4/text-channel.h
HEADERS += ./stubs/TelepathyQt4/contact-manager.h
HEADERS += ./stubs/TelepathyQt4/pending-contacts.h
HEADERS += ./stubs/TelepathyQt4/cli-properties.h
HEADERS += ./stubs/TelepathyQt4/streamed-media-channel.h
HEADERS += ./stubs/TelepathyQt4/account-set.h
HEADERS += ./stubs/TpExtensions/cli-connection.h
HEADERS += ./stubs/notificationmanager.h

SOURCES += ./stubs/TelepathyQt4/pending-operation.cpp
SOURCES += ./stubs/TelepathyQt4/ready-object.cpp
SOURCES += ./stubs/TelepathyQt4/account-manager.cpp
SOURCES += ./stubs/TelepathyQt4/account.cpp
SOURCES += ./stubs/TelepathyQt4/account-set.cpp
SOURCES += ./stubs/TelepathyQt4/types.cpp
SOURCES += ./stubs/TelepathyQt4/pending-ready.cpp
SOURCES += ./stubs/TelepathyQt4/channel.cpp
SOURCES += ./stubs/TelepathyQt4/text-channel.cpp
SOURCES += ./stubs/TelepathyQt4/message.cpp
SOURCES += ./stubs/TelepathyQt4/connection.cpp
SOURCES += ./stubs/TelepathyQt4/contact.cpp
SOURCES += ./stubs/TelepathyQt4/dbus-proxy.cpp
SOURCES += ./stubs/TelepathyQt4/presence.cpp
SOURCES += ./stubs/TelepathyQt4/referenced-handles.cpp
SOURCES += ./stubs/TelepathyQt4/contact-manager.cpp
SOURCES += ./stubs/TelepathyQt4/pending-contacts.cpp
SOURCES += ./stubs/TelepathyQt4/cli-properties.cpp
SOURCES += ./stubs/TelepathyQt4/streamed-media-channel.cpp
SOURCES += ./stubs/notificationmanager.cpp
