/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c AccountPresenceIfAdaptor -a accountpresenceifadaptor AccountPresenceIf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "accountpresenceifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AccountPresenceIfAdaptor
 */

AccountPresenceIfAdaptor::AccountPresenceIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AccountPresenceIfAdaptor::~AccountPresenceIfAdaptor()
{
    // destructor
}

void AccountPresenceIfAdaptor::setAccountPresence(const QString &accountUri, int state)
{
    // handle method call org.nemomobile.AccountPresenceIf.setAccountPresence
    QMetaObject::invokeMethod(parent(), "setAccountPresence", Q_ARG(QString, accountUri), Q_ARG(int, state));
}

void AccountPresenceIfAdaptor::setAccountPresenceWithMessage(const QString &accountUri, int state, const QString &message)
{
    // handle method call org.nemomobile.AccountPresenceIf.setAccountPresenceWithMessage
    QMetaObject::invokeMethod(parent(), "setAccountPresenceWithMessage", Q_ARG(QString, accountUri), Q_ARG(int, state), Q_ARG(QString, message));
}

void AccountPresenceIfAdaptor::setGlobalPresence(int state)
{
    // handle method call org.nemomobile.AccountPresenceIf.setGlobalPresence
    QMetaObject::invokeMethod(parent(), "setGlobalPresence", Q_ARG(int, state));
}

void AccountPresenceIfAdaptor::setGlobalPresenceWithMessage(int state, const QString &message)
{
    // handle method call org.nemomobile.AccountPresenceIf.setGlobalPresenceWithMessage
    QMetaObject::invokeMethod(parent(), "setGlobalPresenceWithMessage", Q_ARG(int, state), Q_ARG(QString, message));
}

