/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c CommHistoryIfAdaptor -a commhistoryifadaptor CommHistoryIf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "commhistoryifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CommHistoryIfAdaptor
 */

CommHistoryIfAdaptor::CommHistoryIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CommHistoryIfAdaptor::~CommHistoryIfAdaptor()
{
    // destructor
}

void CommHistoryIfAdaptor::activateNotification(int groupId, const QString &remoteActionString)
{
    // handle method call org.nemomobile.CommHistoryIf.activateNotification
    QMetaObject::invokeMethod(parent(), "activateNotification", Q_ARG(int, groupId), Q_ARG(QString, remoteActionString));
}

void CommHistoryIfAdaptor::setCallHistoryObserved(bool observed)
{
    // handle method call org.nemomobile.CommHistoryIf.setCallHistoryObserved
    QMetaObject::invokeMethod(parent(), "setCallHistoryObserved", Q_ARG(bool, observed));
}

void CommHistoryIfAdaptor::setInboxObserved(bool observed, const QString &filterAccount)
{
    // handle method call org.nemomobile.CommHistoryIf.setInboxObserved
    QMetaObject::invokeMethod(parent(), "setInboxObserved", Q_ARG(bool, observed), Q_ARG(QString, filterAccount));
}

void CommHistoryIfAdaptor::setInboxObserved(bool observed)
{
    // handle method call org.nemomobile.CommHistoryIf.setInboxObserved
    QMetaObject::invokeMethod(parent(), "setInboxObserved", Q_ARG(bool, observed));
}

void CommHistoryIfAdaptor::setObservedConversations(const QVariantList &conversations)
{
    // handle method call org.nemomobile.CommHistoryIf.setObservedConversations
    QMetaObject::invokeMethod(parent(), "setObservedConversations", Q_ARG(QVariantList, conversations));
}

