/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c VoiceCountersIfAdaptor -a voicecountersifadaptor VoiceCountersIf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VOICECOUNTERSIFADAPTOR_H_1372055385
#define VOICECOUNTERSIFADAPTOR_H_1372055385

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.nemomobile.VoiceCountersIf
 */
class VoiceCountersIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.nemomobile.VoiceCountersIf")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.nemomobile.VoiceCountersIf\">\n"
"    <method name=\"getCounters\">\n"
"      <arg direction=\"out\" type=\"a{si}\" name=\"counters\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"resetCounters\"/>\n"
"    <signal name=\"countersChanged\"/>\n"
"  </interface>\n"
        "")
public:
    VoiceCountersIfAdaptor(QObject *parent);
    virtual ~VoiceCountersIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QVariantMap getCounters();
    void resetCounters();
Q_SIGNALS: // SIGNALS
    void countersChanged();
};

#endif
